IF OBJECT_ID('dbo.[Node]', 'U') IS NOT NULL 
  DROP TABLE dbo.[Node]

CREATE TABLE [dbo].[Node](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Parent_Id] [int] NULL,
	[Value] [int] NOT NULL,
 CONSTRAINT [PK_Period] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Node]  WITH CHECK ADD  CONSTRAINT [FK_Period_Period] FOREIGN KEY([Parent_Id])
REFERENCES [dbo].[Node] ([Id])
GO

ALTER TABLE [dbo].[Node] CHECK CONSTRAINT [FK_Period_Period]
GO